version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Lint
          command: |
            pip install flake8
            flake8 . --exclude=venv*,migrations* --count --select=E9,F63,F7,F82 --ignore=E402,F401 --max-complexity=10 --max-line-length=127 --show-source --statistics
      - run:
          name: Run tests
          command: |
            if [ -f tests/run_tests.sh ]; then bash tests/run_tests.sh; fi

workflows:
  version: 2
  test:
    jobs:
      - test