name: Spjald

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --exclude=venv*,migrations* --count --select=E9,F63,F7,F82 --ignore=E402,F401 --max-complexity=10 --max-line-length=127 --show-source --statistics

    - name: Run tests
      run: |
        if [ -f tests/run_tests.sh ]; then bash tests/run_tests.sh; fi